### ISSUE TITLE
Upgrade to 1.6

### ISSUE THREAD

**Issue by sawilde** [jexp/neo4j-clean-remote-db-addon#3]
Is it possible to upgrade this plug-in to 1.6 - I forked and updated the POM (1.5->1.6, following your last changeset) and recompiled with tests and got the following test error

---
##  T E S T S

Running org.neo4j.server.DeleteDatabaseTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.059 sec <<< FAILURE!

Results :

Tests in error: 
  org.neo4j.server.DeleteDatabaseTest: org/neo4j/server/AddressResolver
  org.neo4j.server.DeleteDatabaseTest: Could not initialize class org.neo4j.server.DeleteDatabaseTest

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

**Comment by jexp** [comment]
Yes, I'll do.

**Comment by jexp** [comment]
Done, new jar available.

**Comment by sawilde** [comment]
Thanks, I'll test it out

The commit for this is 209478d4f79624034777be8ecf2107d5007f487a
