### ISSUE TITLE
README.md is misleading

### ISSUE THREAD

**Issue by Enceradeira** [jexp/neo4j-clean-remote-db-addon#5]
Hi

Please write 
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.test.delete=/db/data/cleandb
instead of
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.test.delete=/cleandb
in the REAMD.md. This is because /db/data/cleandb is the default (according to http://docs.neo4j.org/chunked/stable/server-installation.html). 

I followed your instructions and had an issue with https://github.com/maxdemarzi/neography, that wired to /db/data/cleandb by default.

Cheers
Jorg

**Comment by jexp** [comment]
Thanks, fixed.
