### ISSUE TITLE
Upgrade to 1.7

### ISSUE THREAD

**Issue by pjvds** [jexp/neo4j-clean-remote-db-addon#6]
The latest package that is currently available for v1.6 is not compatible with 1.7. It gives a HTTP1.1 500 error.

**Comment by Benjin** [comment]
+1 for this

**Comment by elado** [comment]
+1 for 1.8

**Comment by yaronn** [comment]
+1 for 1.8

**Comment by pjvds** [comment]
1.8 is pulled today \o/
